language: ruby
cache: bundler
before_script:
  - psql -c 'create database ruby_au_test;' -U postgres >/dev/null
  - bundle exec rake db:create db:schema:load
  - nvm install 10.15
  - yarn install
  - bundle exec rails webpacker:compile
script:
  - bundle exec rubocop
  - bundle exec rspec
services:
  - postgresql
node_js: 12.18
